triggers:
  cron: "@weekly"
environment_variables:
  TOXENV: "py27"
pre_build_script:
  - apt-get -y install xmlsec1
script:
  - virtualenv venv
  - . venv/bin/activate
  - pip install tox
  - tox
  - python setup.py sdist bdist_wheel
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true
