pre_build_script:
  - apt-get -y install xmlsec1
script:
  - virtualenv venv
  - . venv/bin/activate
  - pip install -r tests/test-requirements.txt
  - pip freeze
  - py.test tests
  - python setup.py sdist bdist_wheel
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true
